import path from "node:path";
import { mkdir } from "node:fs/promises";
import { randomUUID } from "node:crypto";

import PptxGenJS from "pptxgenjs";

const GENERATED_ROOT = path.resolve(
    process.cwd(),
    "generated",
    "presentations"
);

function slugify(value, fallback = "presentation") {
    const slug = String(value || "")
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "");

    return slug || fallback;
}

function normalizeSlides(slides) {
    if (!Array.isArray(slides)) {
        return [];
    }

    return slides
        .map((slide) => ({
            title: String(slide?.title || "").trim(),
            content: Array.isArray(slide?.content)
                ? slide.content
                    .map((item) => String(item || "").trim())
                    .filter(Boolean)
                : [],
        }))
        .filter((slide) => slide.title && slide.content.length > 0);
}

export function resolvePresentationPath(fileName) {
    const safeName = path.basename(String(fileName || ""));
    const resolved = path.resolve(GENERATED_ROOT, safeName);

    if (!resolved.startsWith(GENERATED_ROOT)) {
        throw new Error("Invalid presentation file path.");
    }

    return resolved;
}

export async function createPresentationArtifact(presentation) {
    const title = String(presentation?.title || "").trim();
    const slides = normalizeSlides(presentation?.slides);

    if (!title) {
        throw new Error("Presentation title is required.");
    }

    if (slides.length === 0) {
        throw new Error("Presentation requires at least one slide.");
    }

    await mkdir(GENERATED_ROOT, { recursive: true });

    const fileName = `${slugify(title)}-${randomUUID().slice(0, 8)}.pptx`;
    const filePath = resolvePresentationPath(fileName);

    const pptx = new PptxGenJS();
    pptx.layout = "LAYOUT_WIDE";
    pptx.author = "Chaos Engine";
    pptx.company = "Chaos Engine";
    pptx.subject = title;
    pptx.title = title;
    pptx.lang = "en-US";
    pptx.theme = {
        headFontFace: "Aptos Display",
        bodyFontFace: "Aptos",
        lang: "en-US",
    };

    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: "050505" };
    titleSlide.addShape(pptx.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.333,
        h: 7.5,
        line: { color: "050505", transparency: 100 },
        fill: { color: "050505" },
    });
    titleSlide.addShape(pptx.ShapeType.rect, {
        x: 0.7,
        y: 1.0,
        w: 0.18,
        h: 5.4,
        line: { color: "10B981", transparency: 100 },
        fill: { color: "10B981" },
    });
    titleSlide.addText(title, {
        x: 1.1,
        y: 1.5,
        w: 11.2,
        h: 1.4,
        fontFace: "Aptos Display",
        fontSize: 30,
        bold: true,
        color: "FFFFFF",
        valign: "mid",
    });
    titleSlide.addText("Generated by Chaos Engine", {
        x: 1.1,
        y: 3.1,
        w: 6.5,
        h: 0.35,
        fontFace: "Aptos",
        fontSize: 13,
        color: "A3A3A3",
    });
    titleSlide.addText(`${slides.length} slides`, {
        x: 1.1,
        y: 6.55,
        w: 2.0,
        h: 0.25,
        fontFace: "Aptos",
        fontSize: 10,
        color: "737373",
    });

    slides.forEach((slideData, index) => {
        const slide = pptx.addSlide();
        slide.background = { color: "F8FAFC" };
        slide.addShape(pptx.ShapeType.rect, {
            x: 0,
            y: 0,
            w: 13.333,
            h: 0.18,
            line: { color: "10B981", transparency: 100 },
            fill: { color: "10B981" },
        });
        slide.addText(slideData.title, {
            x: 0.8,
            y: 0.55,
            w: 11.8,
            h: 0.6,
            fontFace: "Aptos Display",
            fontSize: 24,
            bold: true,
            color: "111827",
        });
        slide.addText(
            slideData.content.map((item) => ({
                text: item,
                options: {
                    bullet: { indent: 18 },
                },
            })),
            {
            x: 1.0,
            y: 1.55,
            w: 11.5,
            h: 4.9,
            fontFace: "Aptos",
            fontSize: 18,
            color: "1F2937",
            valign: "top",
            margin: 0,
            paraSpaceAfterPt: 12,
            }
        );
        slide.addText(`${index + 1}`, {
            x: 12.4,
            y: 6.95,
            w: 0.45,
            h: 0.18,
            fontFace: "Aptos",
            fontSize: 9,
            color: "94A3B8",
            align: "right",
        });
    });

    await pptx.writeFile({ fileName: filePath });

    return {
        title,
        fileName,
        filePath,
        downloadUrl: `/api/orchestrator/ppt/download/${encodeURIComponent(fileName)}`,
        slideCount: slides.length,
    };
}
